name: "Java CI with Multi-arch Docker Test Image"

on:
  push:
    branches:
      - dev

jobs:
  docker:
    name: Running Compile Java Multi-arch Docker Test Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout diyfile
        uses: actions/checkout@v3
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - run: mkdir -p diyfile-web
      - name: Checkout diyfile-web
        uses: actions/checkout@v3
        with:
          repository: 'besscroft/diyfile-web'
          ref: dev
          path: 'diyfile-web'
      - run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache-dependency-path: 'diyfile-web'
          cache: pnpm
      - run: pnpm i --prefix diyfile-web
      - run: pnpm run --prefix diyfile-web build:vite
      - run: mkdir -p diyfile-system/src/main/resources/static && cp -r diyfile-web/dist/* diyfile-system/src/main/resources/static
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package -Dmaven.test.skip=true --file pom.xml
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push diyfile test
        id: docker_build_diyfile_test
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./.github/docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/diyfile:test
